### PR TITLE
fix(kafka_topic): send false values

### PR DESCRIPTION
**Pull request by byashimov**
## About this change—what it does

- Doesn't submit kafka topic config default values 
- Fix sending `false` values in kafka topic config

### CODE REVIEW

**Comment by byashimov** [comment]
[tests](https://github.com/aiven/terraform-provider-aiven/actions/runs/8702143647)
also, please review carefully and have tested locally

**Comment by Serpentiel** [comment]
[Lint](https://github.com/aiven/terraform-provider-aiven/actions/runs/8719084220/job/23917684453?pr=1691) and [Flink acceptance tests](https://github.com/aiven/terraform-provider-aiven/actions/runs/8719084351/job/23917768127?pr=1691) run failed in the CI

**Comment by byashimov** [comment]
> [Lint](https://github.com/aiven/terraform-provider-aiven/actions/runs/8719084220/job/23917684453?pr=1691) and [Flink acceptance tests](https://github.com/aiven/terraform-provider-aiven/actions/runs/8719084351/job/23917768127?pr=1691) run failed in the CI

Fixed by removing the linter.

**Review by Serpentiel — APPROVED** [review]
lgtm

**Pull request merged**
