### PR TITLE
fix(opensearch): typo

### PR DESCRIPTION
**Pull request by Nico385412**
## About this change—what it does

Fix typo in description

### CODE REVIEW

**Review by ivan-savciuc — APPROVED** [review]
LGTM

**Review by ivan-savciuc — COMMENTED** [review]
Please RUN `make docs` and commit all the newly generated doc files

**Comment by Nico385412** [comment]
should be good now :D

**Review by ivan-savciuc — APPROVED** [review]
Thanks for you contribution

**Pull request merged**
