### PR TITLE
add data source for billing group

### PR DESCRIPTION
**Pull request by simunni**
This PR adds data source support for billing group.

### CODE REVIEW

**Comment by simunni** [comment]
It should be noted that running test fails because data source for billing group doesn't yet exist.
However, after pointing provider to forked repository test seems to pass.

**Comment by mhoffm-aiven** [comment]
Hey @simunni,

Thanks for the contribution! Looks good in principle! Could you please also add a `CHANGELOG.md` entry and docs ( `make docs` + an example in examples/data_sources/aiven_billing_group i think )?

**Comment by mhoffm-aiven** [comment]
Looks good to me! Please dont worry about the failing changelog action, the checks are still a in a WIP state. Could you as a last step squash the commits and mark the PR as `ready for review` ? ( this will trigger the acceptance_tests action )

**Comment by simunni** [comment]
No problem. I hope it's now done correctly.

**Review by mhoffm-aiven — APPROVED** [review]
LGTM, changelog and acceptance tests fail because i misconfigured CI checks. Thanks @simunni

**Pull request merged**
