### PR TITLE
replace deprecated functions after TF SDK v2 upgrade #2

### PR DESCRIPTION
**Pull request by ivan-savciuc**

### CODE REVIEW

**Comment by encima** [comment]
This change is for all calls under `datasource` and `resource` is that right? Tests are unaffected and continue to use the `fmt` module?

**Comment by ivan-savciuc** [comment]
> This change is for all calls under `datasource` and `resource` is that right? Tests are unaffected and continue to use the `fmt` module?

Yep, this is only for `datasource` and `resource`, tests are unaffected.

**Review by encima — CHANGES_REQUESTED** [review]
I would propose to close this as #397 is a related change which we would want in as a single entity in case we need to roll back or just for a clean log. What do you think?

**Comment by ivan-savciuc** [comment]
Ok I will merge these two PRs into one.

**Comment by encima** [comment]
> Ok I will merge these two PRs into one.

Already done #397, we can just close this

**Pull request closed without merging**
