### PR TITLE
pre-release: v3.8.0

### PR DESCRIPTION
**Pull request by ivan-savciuc**
## About this change—what it does

pre-release: v3.8.0

### CODE REVIEW

**Comment by ivan-savciuc** [comment]
running acc-tests: https://github.com/aiven/terraform-provider-aiven/actions/runs/3280857966

**Comment by Serpentiel** [comment]
acceptance tests: https://github.com/aiven/terraform-provider-aiven/actions/runs/3288406500

**Comment by Serpentiel** [comment]
acceptance tests: https://github.com/aiven/terraform-provider-aiven/actions/runs/3288859492

**Comment by ivan-savciuc** [comment]
Running acc-test with the new patch https://github.com/aiven/terraform-provider-aiven/actions/runs/3289490498

**Comment by Serpentiel** [comment]
acceptance tests: https://github.com/aiven/terraform-provider-aiven/actions/runs/3290082980

**Comment by Serpentiel** [comment]
acceptance tests: https://github.com/aiven/terraform-provider-aiven/actions/runs/3290305420

**Review by Serpentiel — APPROVED** [review]
lgtm

**Comment by ivan-savciuc** [comment]
LGTM

**Pull request merged**
