### PR TITLE
fix project create/update

### PR DESCRIPTION
**Pull request by byashimov**
## About this change—what it does

- omits empty `add_account_owners_admin_access` on create
- adds `add_account_owners_admin_access` on update
- updates aiven-go-client

### CODE REVIEW

**Comment by byashimov** [comment]
Blocked by #945 because of new client.

**Review by ivan-savciuc — COMMENTED** [review]
@muralibasani Can you extend one of the Project acc test with this field?

**Review by ivan-savciuc — DISMISSED** [review]
LGTM

**Review by ivan-savciuc — APPROVED** [review]
LGTM

**Pull request merged**
