### PR TITLE
fix billing group data-source

### PR DESCRIPTION
**Pull request by ivan-savciuc**
## About this change—what it does

Fixes the `aiven_billing_group` data-source

## Why this way

The billing group name is not unique; therefore, we have to use `billing_group_id` fields instead of `name` as a required field.

### CODE REVIEW

**Review by Serpentiel — DISMISSED** [review]
lgtm

**Comment by ivan-savciuc** [comment]
UPDATE: also updated `golangci-lint` to the latest

**Review by Serpentiel — DISMISSED** [review]

**Comment by ivan-savciuc** [comment]
I think we can merge this `go_test (1.16.x, ubuntu-latest)` is no longer valid

**Review by Serpentiel — DISMISSED** [review]
lgtm

**Pull request merged**
