### PR TITLE
fix(sweep): use accounts with test prefix

### PR DESCRIPTION
**Pull request by m-novikov**
## About this change—what it does

Fixes not all account sweeping functions operate only on test accounts' objects.

## Why this way

Related accounts objects should only be removed from accounts created by test runs

### CODE REVIEW

**Review by Serpentiel — CHANGES_REQUESTED** [review]
could you please fix your commit message to follow https://conventionalcommits.org/en/v1.0.0/ spec?

you are able to simply copy the name of this PR to achieve that

**Comment by m-novikov** [comment]
> could you please fix your commit message to follow https://conventionalcommits.org/en/v1.0.0/ spec?
> 
> you are able to simply copy the name of this PR to achieve that

Yep, thanks just did that :)

**Comment by Serpentiel** [comment]
I'll rebase your branch to `main` and run the acceptance tests to see if this resolves the problem

**Review by Serpentiel — APPROVED** [review]
lgtm

**Pull request merged**
