### PR TITLE
Add acceptance tests on GitHub Actions

### PR DESCRIPTION
**Pull request by jonatasbaldin**
Hey there, this PR adds a GitHub workflow to run the acceptance tests.

I still need to disable it during the `pull_request`, since it will only run when making a new release.

### CODE REVIEW

**Comment by jonatasbaldin** [comment]
The tests are failing with:
```bash
Error: 403: {"errors":[{"message":"Operation would exceed service node quota","status":403}],"message":"Operation would exceed service node quota"} - 
```

I'm looking into the possible fix.

**Comment by jonatasbaldin** [comment]
hey @ivan-savciuc, this is working now!

can u take a look please?

**Review by ivan-savciuc — APPROVED** [review]
awesome 👍

**Comment by ivan-savciuc** [comment]
@jonatasbaldin thought I cannot see that in the `All checks have passed` list, do you have an idea why?

**Comment by jonatasbaldin** [comment]
It is because I disabled the tests for pull requests and forced push the branch. You should see the tests running only after creating a new tag.

**Pull request merged**
