### PR TITLE
feat(org): add org user group support

### PR DESCRIPTION
**Pull request by ivan-savciuc**
## About this change—what it does

adds support for organization user groups

## Why this way

to have it

### CODE REVIEW

**Review by rsalevsky — COMMENTED** [review]
LGTM

**Review by Serpentiel — DISMISSED** [review]
lgtm

**Comment by Serpentiel** [comment]
@ivan-savciuc please resolve the conflicts

**Review by Serpentiel — APPROVED** [review]
lgtm

**Pull request merged**
