### PR TITLE
chore(project): deprecate obsolete fields

### PR DESCRIPTION
**Pull request by Serpentiel**
## About this change—what it does

removes obsolete fields from `project` resource

## Why this way

they are no longer functioning since the release of organizations

### CODE REVIEW

**Comment by byashimov** [comment]
Please fix tests, first [guess](https://github.com/aiven/terraform-provider-aiven/blob/d84db10f3737d479757bd3848595d5b6b2901e8e/internal/sdkprovider/service/project/project_test.go#L45-L45).

**Review by byashimov — CHANGES_REQUESTED** [review]
Please fix tests, first [guess](https://github.com/aiven/terraform-provider-aiven/blob/d84db10f3737d479757bd3848595d5b6b2901e8e/internal/sdkprovider/service/project/project_test.go#L45-L45).

**Comment by Serpentiel** [comment]
```log
=== RUN   TestAccAivenProject_basic
=== PAUSE TestAccAivenProject_basic
=== CONT  TestAccAivenProject_basic
--- PASS: TestAccAivenProject_basic (30.76s)
PASS
```

**Comment by Serpentiel** [comment]
acceptance tests: https://github.com/aiven/terraform-provider-aiven/actions/runs/6149919915

**Review by byashimov — APPROVED** [review]
lgtm

**Pull request merged**
