### PR TITLE
test(account): fix failing team tests

### PR DESCRIPTION
**Pull request by Serpentiel**
## About this change—what it does

fixes failing team test

## Why this way

to make them work

### CODE REVIEW

**Review by ivan-savciuc — CHANGES_REQUESTED** [review]
Replacing the account as an organization under the hood is not a good idea. We should request a change of permissions for our CI projects to test the same API and underlying logic that our customers do, those who are stuck with the accounts, and we have most such customers right now.

**Comment by Serpentiel** [comment]
this never replaced anything with an organization, its simply an env variable name, because the entity was renamed from `account` to `organization`, but as you can see, under the hood it uses `aiven_account` data source

**Comment by Serpentiel** [comment]
acceptance tests (ignore everything except `account`): https://github.com/aiven/terraform-provider-aiven/actions/runs/6609605992/job/17950010317

**Comment by Serpentiel** [comment]
@mhoffm-aiven thanks for helping to set things up from the CI side of things 🥂

**Review by ivan-savciuc — APPROVED** [review]
LGTM

**Pull request merged**
