### PR TITLE
fix(common): GetServiceUserValidateFunc

### PR DESCRIPTION
**Pull request by Serpentiel**
## About this change—what it does

fixes `GetServiceUserValidateFunc`

## Why this way

it didn't match the error message it threw

### CODE REVIEW

**Review by ivan-savciuc — DISMISSED** [review]
LGTM

**Comment by byashimov** [comment]
Could you please provide any tests for those changes?

**Comment by Serpentiel** [comment]
> Could you please provide any tests for those changes?

there are tests, the unit tests and the acceptance tests

**Review by ivan-savciuc — APPROVED** [review]
LGTM

**Pull request merged**
