### PR TITLE
Various documentation fixes

### PR DESCRIPTION
**Pull request by z0r1k**
Fixing typos in:
* `pg_read_replica`, `read_replica`
* `os_acls_config`

### CODE REVIEW

**Review by dmitrii-vasilev — APPROVED** [review]
Looks good

**Comment by z0r1k** [comment]
Are tests a bit flaky? Because it looks like some of them are failed, but they don't seem to be related to the changes in this PR 🤔

**Comment by mhoffm-aiven** [comment]
CI project is out of credits; and the tests are flaky, working on it on a different PR

**Review by mhoffm-aiven — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
