### PR TITLE
added mysql code

### PR DESCRIPTION
**Pull request by ravindrasinghh**
Please vote on this pull request by adding :+1: ,comments to help the community

### CODE REVIEW

**Review by ivan-savciuc — CHANGES_REQUESTED** [review]
@ravindrasinghh, thanks for this. I want to request some changes to make it consistent with our existing documentation and examples. 

- Please reduce input variables to `Aiven Token` and maybe project name if we need to. 
- Change provider version to `version = "2.X.X"`
- Add a link to this example folder to our docs index page `docs/index.md`

**Comment by ravindrasinghh** [comment]
hi @ivan-savciuc 
Code has been updated with the above comments.
please check and let me know if anything missing.

**Review by ivan-savciuc — CHANGES_REQUESTED** [review]
We still use some of the variables in the MySQL resource, though they do no longer exist.

**Comment by ivan-savciuc** [comment]
And please squash it all to one commit.

**Comment by ravindrasinghh** [comment]
@ivan-savciuc 
added the code as  per comment.

**Review by ivan-savciuc — APPROVED** [review]

**Comment by ravindrasinghh** [comment]
Thanks @ivan-savciuc

**Pull request merged**
