### PR TITLE
add support for new kafka topic features

### PR DESCRIPTION
**Pull request by ivan-savciuc**
- use new Kafka Topic config
- deprecate old fields
- change Kafka Topic cache, since list API method does not retrieve `config`
- update docs

### CODE REVIEW

**Comment by rikonen** [comment]
Conflicts, otherwise lgtm

**Comment by ivan-savciuc** [comment]
Updated branch, all conflicts resolved.

**Comment by ivan-savciuc** [comment]
It looks like a glitch: https://travis-ci.org/github/aiven/terraform-provider-aiven/builds/736375826 Travis CI job has finished, but here on the GitHub it is still in progress.

**Comment by rikonen** [comment]
Commit in the build you linked doesn't match this pull request so I think it just never started a new one.

**Review by rikonen — APPROVED** [review]

**Pull request merged**
