### PR TITLE
fix workflow formatting

### PR DESCRIPTION
**Pull request by Serpentiel**
## About this change—what it does

fixes workflow formatting

there's going to be a bunch of clean up PRs, I will add a changelog entry for it with the last PR

## Why this way

to improve the formatting

### CODE REVIEW

**Review by ivan-savciuc — COMMENTED** [review]
Not sure what value it has. For my money, yaml compact array notation is better for perception

**Comment by Serpentiel** [comment]
> Not sure what value it has. For my money, yaml compact array notation is better for perception

it's easier to maintain for humans, the compact notation is used for machine-generated arrays which involve no human maintenance

**Comment by mhoffm-aiven** [comment]
> > Not sure what value it has. For my money, yaml compact array notation is better for perception
> 
> it's easier to maintain for humans, the compact notation is used for machine-generated arrays which involve no human maintenance

I, as a human, kinda like the compact arrays. But i also dont mind the expanded notation, if you have strong feelings about this the PR looks good to me.

**Comment by Serpentiel** [comment]
> > > Not sure what value it has. For my money, yaml compact array notation is better for perception
> > 
> > 
> > it's easier to maintain for humans, the compact notation is used for machine-generated arrays which involve no human maintenance
> 
> I, as a human, kinda like the compact arrays. But i also dont mind the expanded notation, if you have strong feelings about this the PR looks good to me.

it's not the only change in this PR though—we can fallback to the compact notation, but I don't know why?

the fluent notation takes only one key press in an IDE to add a new option to it, while the compact notation takes at least 2 key presses :)

**Review by mhoffm-aiven — APPROVED** [review]
lgtm

**Pull request merged**
