### PR TITLE
fix kafka topic creation typo

### PR DESCRIPTION
**Pull request by ivan-savciuc**
Fixes incorrect handling of an already exists error during creation of the topic.

### CODE REVIEW

**Review by encima — COMMENTED** [review]
Is there a test for this? Good that we fixed it but adding test cases alongside fixes would be good also

**Comment by ivan-savciuc** [comment]
@encima good point, I will try to add a test later today, it will require to run some API calls to create a topic before TF is allowed to do that. I'm not sure if we have a granularity of such level available in the TF Testing framework.

**Comment by encima** [comment]
ah, that may be a bigger task then. We could use the OpenAPI spec to create a mock API layer to handle the calls (could be useful in the operator as well then). If you agree then I will merge this and create a ticket to add that functionality (which you can assign to me to do or help out with)?

**Comment by ivan-savciuc** [comment]
I found a way to validate that logic using `PreConfig` function, and all looks to be straight forward. I will soon add tests.

**Comment by ivan-savciuc** [comment]
Added tests

**Review by encima — APPROVED** [review]

**Pull request merged**
