### PR TITLE
replace aiven/tfprovidertestfmt with katbyte/terrafmt

### PR DESCRIPTION
**Pull request by Serpentiel**
we're replacing our in-house solution with a community-supported tool so we can avoid being the sole supporter for the formatting tool

jfyi, the way blocks are indented was changed because of the new tool's behavior
it has been fixed by @mhoffm-aiven in https://github.com/katbyte/terrafmt/pull/60, and we're currently waiting for the repository maintainers to merge it in the upstream

### CODE REVIEW

**Review by ivan-savciuc — COMMENTED** [review]
Is it possible to configure this tool to have a bunch of tags or an offset to look it a bit more like it was before? Otherwise LGTM

**Comment by ivan-savciuc** [comment]
also pls rebase to the latest master

**Comment by Serpentiel** [comment]
> Is it possible to configure this tool to have a bunch of tags or an offset to look it a bit more like it was before? Otherwise LGTM

@mhoffm-aiven pointed me out that they'll see what could be done

**Comment by Serpentiel** [comment]
I believe we can merge this, indentation support will probably be coming in future releases of the tool
@mhoffm-aiven what do you think?

**Review by mhoffm-aiven — APPROVED** [review]
lgtm

**Review by ivan-savciuc — APPROVED** [review]
LGTM, please rebase and we will merge

**Pull request merged**
