### PR TITLE
docs: fix link to organizations documentation

### PR DESCRIPTION
**Pull request by ArthurFlag**

### CODE REVIEW

**Review by rriski — APPROVED** [review]

**Comment by ArthurFlag** [comment]
@rriski  Turns out I can't merge the PR, so if you can, please do 😊

**Comment by rriski** [comment]
> @rriski Turns out I can't merge the PR, so if you can, please do 😊

It looks like the branch is not up to date with main, could you rebase it on latest `main`?

**Comment by ArthurFlag** [comment]
Done!

**Comment by rriski** [comment]
> Done!

Looks like there are no changes now, the link was already updated some time ago in https://github.com/aiven/terraform-provider-aiven/pull/1761

**Comment by byashimov** [comment]
Hey. Thanks for the contribution! It looks like it was fixed two month ago https://github.com/aiven/terraform-provider-aiven/commit/6d6f72e4915253ef8e5f57b3865b12171ae667cd
Or do I miss something?

**Pull request closed without merging**
