### PR TITLE
Update to sdk

### PR DESCRIPTION
**Pull request by stack72**
This was simple mechanical changes - the provider functionality is completely untouched, except for 1 simple function replacement due to it being deprecated

I used the guide https://www.terraform.io/docs/extend/plugin-sdk.html to run the migration. I needed to upgrade to the minimum of 0.12.7 of Terraform before starting the migration

The migration check then gave me the following output

```
$ tf-sdk-migrator check
Checking Go runtime version ...
Go version 1.13.9: OK.
Checking whether provider uses Go modules...
Go modules in use: OK.
Checking version of github.com/hashicorp/terraform-plugin-sdk to determine if provider was already migrated...
Checking version of github.com/hashicorp/terraform used in provider...
Terraform version 0.12.7: OK.
Checking whether provider uses deprecated SDK packages or identifiers...
No imports of deprecated SDK packages or identifiers: OK.

All constraints satisfied. Provider can be migrated to the new SDK.
```

I was then able to run the actual migrate command

```
$ tf-sdk-migrator migrate
Checking Go runtime version ...
Go version 1.13.9: OK.
Checking whether provider uses Go modules...
Go modules in use: OK.
Checking version of github.com/hashicorp/terraform-plugin-sdk to determine if provider was already migrated...
Checking version of github.com/hashicorp/terraform used in provider...
Terraform version 0.12.7: OK.
Checking whether provider uses deprecated SDK packages or identifiers...
No imports of deprecated SDK packages or identifiers: OK.

All constraints satisfied. Provider can be migrated to the new SDK.

Rewriting provider go.mod file...
Rewriting SDK package imports...
Running `go mod tidy`...
Success! Provider is migrated to github.com/hashicorp/terraform-plugin-sdk v1.7.0.

It looks like this provider vendors dependencies. Don't forget to run `go mod vendor`.
Make sure to review all changes and run all tests.
```

### CODE REVIEW

**Comment by ivan-savciuc** [comment]
Thanks for preparing this PR, according to Aivan internal roadmap we will have a green light to migrate to the SDK after merging this PR https://github.com/aiven/terraform-provider-aiven/pull/171, and it is blocked at the moment by some issues on Aiven API side. 

Otherwise LGTM, I will ping you/test and review again when the blocker is off the tables. 

A bit of a background, many Aiven customers are big enterprises, and we know that it will take time for them to upgrade their Terraform => 0.12.X. Therefore we have a minimum list of features that have to be supported for 0.11.X TF clients, including https://github.com/aiven/terraform-provider-aiven/pull/171.

**Comment by mteiste** [comment]
Converted to draft while it waits for the PR #171

**Comment by stack72** [comment]
Hi @mteiste / @ivan-savciuc 

Just circling back on this now that #171 has been merged and a new release has gone out

Paul

**Comment by ivan-savciuc** [comment]
Hi @stack72, can you please update this PR with the latest master? We can move forward with the SDK update.

**Comment by stack72** [comment]
Hi @ivan-savciuc 

Rebased and updated as requested 

Paul

**Comment by stack72** [comment]
Hi @ivan-savciuc 

Just checking in :D

Paul

**Comment by ivan-savciuc** [comment]
Hi Paul,

Sorry for the delay. 

I was on vacation, and also we have been finalizing our new major release strategy for Terraform. Running some final tests, and will come back to soon. 

Ivan

**Comment by stack72** [comment]
> Hi Paul,
> 
> Sorry for the delay.
> 
> I was on vacation, and also we have been finalizing our new major release strategy for Terraform. Running some final tests, and will come back to soon.
> 
> Ivan

No worries at all :) I am just checking in. BTW, can I email you direct about the provider? Would be interested in telling you what I am doing with it

Thanks

Paul

**Comment by ivan-savciuc** [comment]
Of course, my email savciuci@aiven.io

Ivan

**Pull request merged**
